//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Master
    {
        public int AId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Services { get; set; }
        public Nullable<System.DateTime> Apply_DT { get; set; }
    }
}
