//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryMaster
    {
        public string Name { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string AdharNo { get; set; }
        public Nullable<int> RelatedStateId { get; set; }
        public Nullable<int> RelatedCityId { get; set; }
        public Nullable<int> RelatedBlockId { get; set; }
        public string VillageName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string BeneficiaryPicName { get; set; }
        public string AdharPicName { get; set; }
        public Nullable<System.DateTime> RegDT { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual City_Master City_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
