//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block_Master
    {
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public int CityId { get; set; }
    
        public virtual City_Master City_Master { get; set; }
    }
}
