//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City_Master()
        {
            this.BeneficiaryMasters = new HashSet<BeneficiaryMaster>();
            this.Block_Master = new HashSet<Block_Master>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryMaster> BeneficiaryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Block_Master> Block_Master { get; set; }
        public virtual City_Master City_Master1 { get; set; }
        public virtual City_Master City_Master2 { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
