//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry_Master
    {
        public int EnquiryId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> MobNo { get; set; }
        public string Topic { get; set; }
        public string Enquiry_Msg { get; set; }
        public Nullable<System.DateTime> Enquiry_dt { get; set; }
    }
}
