//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Master
    {
        public string UserId { get; set; }
        public string UserType { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> LCount { get; set; }
        public Nullable<System.DateTime> LastLogin_dt { get; set; }
    }
}
