//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Panchyat_DBEntities : DbContext
    {
        public Panchyat_DBEntities()
            : base("name=Panchyat_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apply_Master> Apply_Master { get; set; }
        public virtual DbSet<BeneficiaryMaster> BeneficiaryMasters { get; set; }
        public virtual DbSet<Block_Master> Block_Master { get; set; }
        public virtual DbSet<City_Master> City_Master { get; set; }
        public virtual DbSet<Enquiry_Master> Enquiry_Master { get; set; }
        public virtual DbSet<Feedback_Master> Feedback_Master { get; set; }
        public virtual DbSet<Login_Master> Login_Master { get; set; }
        public virtual DbSet<Notification_Master> Notification_Master { get; set; }
        public virtual DbSet<Service_Master> Service_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
    }
}
