//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGramPanchayat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Master
    {
        public int Id { get; set; }
        public string Services { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Service_DT { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
